FROM ubuntu:latest

WORKDIR /usr/src/app

COPY example-frontend .

ENV REACT_APP_BACKEND_URL=http://localhost:8080

EXPOSE 5000

RUN apt update
RUN apt install -y curl

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash
RUN apt install -y nodejs

RUN npm install
RUN npm run build
RUN npm install -g serve

CMD [ "serve", "-s", "-l", "5000", "build" ]
